Repository tigroo31/its-client, pull requests merged in 2021-09, with the labels that each got.

#13 Add cpm
  rust/Dockerfile
  rust/its-client/Cargo.toml
  rust/libits-client/Cargo.toml
  rust/libits-client/src/lib.rs
  rust/libits-client/src/mqtt/mqtt_client.rs
  rust/libits-client/src/mqtt/mqtt_router.rs
  rust/libits-client/src/pipeline.rs
  rust/libits-client/src/reception/exchange/collective_perception_message.rs
  rust/libits-client/src/reception/exchange/message.rs
  rust/libits-client/src/reception/exchange/mod.rs
  rust/libits-client/src/reception/information.rs
  rust/libits-client/src/shared_channel.rs
  rust/libits-copycat/Cargo.toml
  rust/libits-copycat/src/lib.rs
Labels: enhancement

#16 Make necessary mods public
  rust/libits-client/src/mqtt/topic/mod.rs
  rust/libits-client/src/reception/exchange/mod.rs
  rust/libits-client/src/reception/mortal.rs
Labels: enhancement

#17 Manage perceived object
  .github/workflows/crates.yml
  rust/libits-client/Cargo.toml
  rust/libits-client/src/reception/exchange/collective_perception_message.rs
  rust/libits-client/src/reception/exchange/mobile.rs
  rust/libits-client/src/reception/exchange/mobile_perceived_object.rs
  rust/libits-client/src/reception/exchange/mod.rs
  rust/libits-client/src/reception/exchange/perceived_object.rs
  rust/libits-client/src/reception/exchange/reference_position.rs
Labels: enhancement

#19 Switch debug to trace logs to reduce flooding
  rust/libits-client/src/mqtt/mqtt_router.rs
  rust/libits-client/src/pipeline.rs
Labels: enhancement

#18 Add etsi json schema
  .github/workflows/crates.yml
  .github/workflows/doc.yml
  .github/workflows/docker.yml
  rust/Dockerfile
  rust/its-client/Cargo.toml
  rust/libits-client/Cargo.toml
  rust/libits-copycat/Cargo.toml
  schema/cam_schema_1-1-0.json
  schema/cpm_schema_1-0-0.json
  schema/denm_schema_1-1-0.json
  schema/information_schema_1-0-3.json
Labels: bug, documentation

#20 Fix docker parameters
  action.yml
  rust/Dockerfile
  rust/docker-entrypoint.sh
  rust/its-client/Cargo.toml
  rust/its-client/src/main.rs
  rust/libits-client/Cargo.toml
  rust/libits-client/src/reception/exchange/collective_perception_message.rs
  rust/libits-client/src/reception/exchange/mobile.rs
  rust/libits-client/src/reception/exchange/mobile_perceived_object.rs
  rust/libits-client/src/reception/exchange/reference_position.rs
  schema/information_schema_1-0-6.json
Labels: bug

#22 Provide denm path
  rust/libits-client/Cargo.toml
  rust/libits-client/src/pipeline.rs
  rust/libits-client/src/reception/exchange/collective_perception_message.rs
  rust/libits-client/src/reception/exchange/message.rs
  rust/libits-client/src/reception/exchange/mobile_perceived_object.rs
  rust/libits-client/src/reception/exchange/mod.rs
  schema/cam_schema_1-1-1.json
  schema/cpm_schema_1-0-1.json
  schema/denm_schema_1-1-1.json
Labels: enhancement

#23 Read information
  rust/libits-client/Cargo.toml
  rust/libits-client/src/reception/exchange/collective_perception_message.rs
  rust/libits-client/src/reception/exchange/mobile_perceived_object.rs
  rust/libits-client/src/reception/information.rs
  rust/libits-client/src/reception/mod.rs
Labels: bug, enhancement
